### ISSUE TITLE
Xtabline may has a load order problem when lazy_mode is on

### ISSUE THREAD

**Issue by 66RING** [mg979/vim-xtabline#17] opened 2020-09-29 11:33 UTC
```
let g:xtabline_lazy = 1
let g:xtabline_settings = get(g:, 'xtabline_settings', {})
let g:xtabline_settings.tabline_modes = ['buffers']
let g:xtabline_settings.enable_mappings = 0
let g:xtabline_settings.buffer_filtering = 0
let g:xtabline_settings.tab_number_in_buffers_mode = 0
```

Hello

Xtabline may has a load order problem when lazy_mode is on. If Xtabline has been started or inited this bug will not happen. It seems like an bug.

When open an buffer in vim, tabline should contain two buffers, the old one and the new open one. But Xtabline don't do that (since 34485e367289bf80a0e6d36f8bc8386ff02ca44f) and only contain an new open buffer.

## Expect

Open an buffer in the open vim, Xtabline init and contains two buffers not just the new open one.

If `autoload/xtabline.vim` in 34485e367289bf80a0e6d36f8bc8386ff02ca44f, line 24, is `let s:ready = { -> !exists('g:SessionLoad') || get(s:v, 'filter_buffers', 0) }` wil be good. But I don't know any detail about this.

**Comment by 66RING** [comment] 2020-09-29 12:17
#### bug one

![bug_one](https://user-images.githubusercontent.com/49358576/94557042-9e574e00-0290-11eb-9fb3-53c70047ccb8.gif)

#### expected one

![fixed_one](https://user-images.githubusercontent.com/49358576/94557054-a0b9a800-0290-11eb-9b7c-40ec554ffb1d.gif)

**Comment by mg979** [comment] 2020-09-30 00:17
Did you update master? I cannot reproduce with this vimrc:
```vim
set nocompatible
set runtimepath=$VIMRUNTIME
set packpath=
set runtimepath+=/path/to/vim-xtabline
set showtabline=2

let g:xtabline_lazy = 1
let g:xtabline_settings = get(g:, 'xtabline_settings', {})
let g:xtabline_settings.tabline_modes = ['buffers']
let g:xtabline_settings.enable_mappings = 0
let g:xtabline_settings.buffer_filtering = 0
let g:xtabline_settings.tab_number_in_buffers_mode = 0
```

Then

    vim -u testrc somefile

**Comment by 66RING** [comment] 2020-09-30 04:47
I find out what went wrong. 

`set hidden` option made this happen.

**Comment by mg979** [comment] 2020-09-30 05:34
`set hidden` can't do that.

**Comment by mg979** [comment] 2020-09-30 05:44
It should be fixed now, please reopen if it's not for you.

**Closed** 2020-09-30 05:43 UTC
